# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    yarn install --frozen-lockfile
    cp .env.template .env
    yarn build
  displayName: 'yarn install and build'
  
- task: DownloadSecureFile@1
  name: gCloudCert
  inputs:
    secureFile: 'oleix2-c9a93f41d28a.json'

- task: GcloudRunner@0
  inputs:
    command: 'auth activate-service-account'
    arguments: '--key-file $(gCloudCert.secureFilePath)'

- task: GcloudRunner@0
  inputs:
    command: 'app deploy --stop-previous-version --project oleix2'
